### ISSUE TITLE
Errors when running in large real world active directory

### ISSUE THREAD

**Issue by ss23** [Group3r/Group3r#1]
I have tested this in a large real world environment. Unfortunately I cannot provide the actual test cases.

Here are some of the errors when running:
```
2021-09-21 12:47:00 +12:00 [Error] Something has gone wrong parsing \\xxx\sysvol\xxx\Policies\{1652C1E6-FC87-44DF-909B-28467B20C9A7}\Machine\microsoft\windows nt\SecEdit\GptTmpl.inf
```
[gpt.txt](https://github.com/Group3r/Group3r/files/7199414/gpt.txt)
An example of a file that does not parse is attached (just one, as there may be others).

Other errors include:
```
2021-09-21 12:47:33 +12:00 [Error] Something went wrong with the scripts.ini parsing and the int casting and the GLAYVIN!
```

```
2021-09-21 12:55:14 +12:00 [Error] Failure processing setting from /r/nSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Group3r.Assessment.Analysers.SchedTaskAnalyser.Analyse(AssessmentOptions assessmentOptions)
   at Group3r.GroupCon.<>c__DisplayClass11_1.<EnqueueGpoTasks>b__0()
2021-09-21 12:55:14 +12:00 [GPO]
| GPO             | GPO/GPP - User - Outlook Profile Creation {1A388170-8896-4FE5-B846-2AAFA7A955B6} Current |
|-----------------|------------------------------------------------------------------------------------------|
| Date Created    | 10/09/2015 10:43:26 AM                                                                   |
| Date Modified   | 13/12/2017 2:31:17 AM                                                                    |
| Path in SYSVOL  | \\redacted.com\sysvol\redacted.com\Policies\{1A388170-8896-4FE5-B846-2AAFA7A955B6}       |
| Computer Policy | Disabled                                                                                 |
| User Policy     | Enabled                                                                                  |
| Link            | LDAP://redacted.com/OU=Company Users,DC=redacted,DC=co,DC=nz (Enabled, Unenforced)          |

    | Finding     | Placeholder |
    |-------------|-------------|
    | Placeholder | Placeholder |
```

```
2021-09-21 12:46:32 +12:00 [Error] Something went wrong inserting GPO links into the GPO objects.System.ArgumgeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.DirectoryServices.ResultPropertyValueCollection.get_Item(Int32 index)
   at LibSnaffle.ActiveDirectory.ActiveDirectory.EnumerateDomainGpoLinks() in Z:\tcfox On My Mac\Source\Repos\Group3r\Group3r\LibSnaffle\ActiveDirectory\ActiveDirectory.cs:line 364
```

Understand these are probably unrelated issues and might not be able to be fixed without examples.

**Comment by ss23** [comment]
Another:
```
2021-09-21 12:54:38 +12:00 [Error] Failure processing setting from /r/nSystem.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at LibSnaffle.Classifiers.DirClassifier.Classify(ClassifierRule classifierRule, String dir) in Z:\tcfox On My Mac\Source\Repos\github.com\Group3r\Group3r\LibSnaffle\Classifiers\DirClassifier.cs:line 18
   at Group3r.Assessment.PathAnalyser.AnalyseDirPath(String dirPath)
   at Group3r.Assessment.PathAnalyser.AnalysePath(String originalPath)
   at Group3r.Assessment.Analysers.FileAnalyser.Analyse(AssessmentOptions assessmentOptions)
   at Group3r.GroupCon.<>c__DisplayClass11_1.<EnqueueGpoTasks>b__0()
```
