### ISSUE TITLE
Parsing malformated sysvol file

### ISSUE THREAD

**Issue by andersnese** [Group3r/Group3r#19]
Running Group3r.exe towards a GPO with malformated sysvol file throws an excetion that is never catched. Ideally this should not make the program halt. 

Command:
`group3r.exe -f output.log -e -a 4 -w -r -v trace`

Output:
```
2022-11-22 11:12:36 +01:00 [Trace] Looking inside file \\corp.net\sysvol\corp.net\Policies\{36123915-EABC-4A25-9C95-1234A25657D3}\User\Documents & Settings\int.xml for settings.
2022-11-22 11:12:37 +01:00 [Error] System.Xml.XmlException: There are multiple root elements. Line 13, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at LibSnaffle.ActiveDirectory.XmlGpoFile.ContentXML()
   at LibSnaffle.ActiveDirectory.XmlGpoFile.GetSettings()
   at LibSnaffle.ActiveDirectory.Sysvol.EnumerateSysvolGpos(List`1 gpoDirs)
   at LibSnaffle.ActiveDirectory.Sysvol..ctor(String sysvolPath, BlockingMq logger)
   at LibSnaffle.ActiveDirectory.SysvolHelper.LoadSysvolOnlineByDc(String targetDomain, String targetDc)
   at LibSnaffle.ActiveDirectory.ActiveDirectory.LoadSysvolOnline(SysvolHelper helper)
   at Group3r.GroupCon.Execute()
2022-11-22 11:12:37 +01:00 [Fatal] Terminate was called
```

This is the int.xml file it breaks on:
```xml
<LayoutModificationTemplate Version="1" xmlns="http://schemas.microsoft.com/Start/2014/LayoutModification">
  <LayoutOptions StartTileGroupCellWidth="6" />
  <DefaultLayoutOverride>
    <StartLayoutCollection>
      <defaultlayout:StartLayout GroupCellWidth="6" xmlns:defaultlayout="http://schemas.microsoft.com/Start/2014/FullDefaultLayout">
        <start:Group Name="" xmlns:start="http://schemas.microsoft.com/Start/2014/StartLayout">
          <start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="..." />
        </start:Group>
      </defaultlayout:StartLayout>
    </StartLayoutCollection>
  </DefaultLayoutOverride>
</LayoutModificationTemplate>
<CustomTaskbarLayoutCollection>
      <defaultlayout:TaskbarLayout>
        <taskbar:TaskbarPinList>
          <taskbar:DesktopApp DesktopApplicationLinkPath="... />
        </taskbar:TaskbarPinList>
      </defaultlayout:TaskbarLayout>
    </CustomTaskbarLayoutCollection>
</LayoutModificationTemplate>
```

**Comment by l0ss** [comment]
Good catch and well-reported - appreciate it. Very simple fix, has now been pushed to main.
