### ISSUE TITLE
Error when running Group3r from a non-domain joined machine

### ISSUE THREAD

**Issue by sdcampbell** [Group3r/Group3r#8]
I am able to browse the netlogon and sysvol shares from a runas cmd window, but Group3r still fails. I have redacted the following information in [ ] tags:

```
C:\tools\Group3r>Group3r.exe -c [fqdn] -d [domain] -f group3r.log -w -a 3 -e
  .,-:::::/ :::::::..       ...      ...    :::::::::::::.  .::.   :::::::..
,;;-'````'  ;;;;``;;;;   .;;;;;;;.   ;;     ;;; `;;;```.;;;;'`';;, ;;;;``;;;;
[[[   [[[[[[/[[[,/[[['  ,[[     \[[,[['     [[[  `]]nnn]]'    .n[[  [[[,/[[['
'$$c.    '$$ $$$$$$c    $$$,     $$$$$      $$$   $$$''      ``'$$$ $$$$$$c
 `Y8bo,,,o88o888b '88bo,'888,_ _,88P88    .d888   888o       ,,o888 888b'''8b,
   `'YMUP'YMMMMMM  'W'   'YMMMMMP'  'YmmMMMM''   YMMMb      YMMP'  MMMM   'WM;
                                                    github.com/Group3r/Group3r
                                                            @mikeloss

Gaze not into the abyss, lest you become recognized as an abyss domain expert,
and they expect you keep gazing into the damn thing... - @nickm_tor


2022-04-12 12:42:01 -04:00 [Info] Parsed args successfully.
2022-04-12 12:42:02 -04:00 [Error] LibSnaffle.Errors.ActiveDirectoryException: Problem figuring out DirectoryContext and/or DCs, you might need to fix your DNS, or define manually with -d and/or -c. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LibSnaffle.ActiveDirectory.LDAP.DirectorySearch..ctor(String domainName, String domainController, String ldapUserName, String ldapPassword, Int32 ldapPort, Boolean secureLdap)
   at LibSnaffle.ActiveDirectory.ActiveDirectory.GetDirectorySearch()
   --- End of inner exception stack trace ---
   at LibSnaffle.ActiveDirectory.ActiveDirectory.GetDirectorySearch()
   at LibSnaffle.ActiveDirectory.ActiveDirectory..ctor(BlockingMq mq, String targetDomain, String targetDc)
   at Group3r.GroupCon.Execute()
2022-04-12 12:42:02 -04:00 [Fatal] Terminate was called

C:\tools\Group3r>net use \\[fqdn]\sysvol
The command completed successfully.


C:\tools\Group3r>dir \\[fqdn]\sysvol
 Volume in drive \\[fqdn]\sysvol is OS
 Volume Serial Number is [redacted]

 Directory of \\[fqdn]\sysvol

10/27/2017  01:43 PM    <DIR>          .
10/27/2017  01:43 PM    <DIR>          ..
10/27/2017  01:43 PM    <JUNCTION>     [domain] [C:\Windows\SYSVOL\domain]
               0 File(s)              0 bytes
               3 Dir(s)  30,571,073,536 bytes free

C:\tools\Group3r>Group3r.exe -c [DC IP] -d [domain] -f group3r.log -w -a 3 -e
  .,-:::::/ :::::::..       ...      ...    :::::::::::::.  .::.   :::::::..
,;;-'````'  ;;;;``;;;;   .;;;;;;;.   ;;     ;;; `;;;```.;;;;'`';;, ;;;;``;;;;
[[[   [[[[[[/[[[,/[[['  ,[[     \[[,[['     [[[  `]]nnn]]'    .n[[  [[[,/[[['
'$$c.    '$$ $$$$$$c    $$$,     $$$$$      $$$   $$$''      ``'$$$ $$$$$$c
 `Y8bo,,,o88o888b '88bo,'888,_ _,88P88    .d888   888o       ,,o888 888b'''8b,
   `'YMUP'YMMMMMM  'W'   'YMMMMMP'  'YmmMMMM''   YMMMb      YMMP'  MMMM   'WM;
                                                    github.com/Group3r/Group3r
                                                            @mikeloss

Gaze not into the abyss, lest you become recognized as an abyss domain expert,
and they expect you keep gazing into the damn thing... - @nickm_tor


2022-04-12 12:44:10 -04:00 [Info] Parsed args successfully.
2022-04-12 12:44:11 -04:00 [Error] LibSnaffle.Errors.ActiveDirectoryException: Problem figuring out DirectoryContext and/or DCs, you might need to fix your DNS, or define manually with -d and/or -c. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LibSnaffle.ActiveDirectory.LDAP.DirectorySearch..ctor(String domainName, String domainController, String ldapUserName, String ldapPassword, Int32 ldapPort, Boolean secureLdap)
   at LibSnaffle.ActiveDirectory.ActiveDirectory.GetDirectorySearch()
   --- End of inner exception stack trace ---
   at LibSnaffle.ActiveDirectory.ActiveDirectory.GetDirectorySearch()
   at LibSnaffle.ActiveDirectory.ActiveDirectory..ctor(BlockingMq mq, String targetDomain, String targetDc)
   at Group3r.GroupCon.Execute()
2022-04-12 12:44:11 -04:00 [Fatal] Terminate was called
```

**Comment by l0ss** [comment]
Pretty sure I remember us figuring out that this was an issue with using kerberos auth over socks? If I'm mistaken and we never figured this out, please reopen.
